name: CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  # Job 1: Build and Push Docker Images
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    strategy:
      matrix:
        service: [auth, product, order, api-gateway]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image - ${{ matrix.service }}
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/eproject-${{ matrix.service }}:latest
          ${{ secrets.DOCKER_USERNAME }}/eproject-${{ matrix.service }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/eproject-${{ matrix.service }}:latest
        cache-to: type=inline

  # Job 2: Deploy Notification
  notify:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: always()
    
    steps:
    - name: Send notification
      run: |
        echo "Build completed with status: ${{ needs.build-and-push.result }}"
        echo "Commit SHA: ${{ github.sha }}"
        echo "Triggered by: ${{ github.actor }}"
